
import React from "react";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>Licenced Number Plate Detection</title>
      </head>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
